import test from 'node:test'; import assert from 'node:assert/strict'; import net from 'node:net'; import { crc24q } from '../rtcm.mjs';
process.env.NODE_ENV='test'; const { nmeaCoordinate, makeGga, validate, LoadTest } = await import('../server.mjs');
test('formats NMEA coordinates',()=>{assert.deepEqual(nmeaCoordinate(52.3676,'N','S',true),{value:'5222.0560',hemisphere:'N'});assert.deepEqual(nmeaCoordinate(-4.9041,'E','W',false),{value:'00454.2460',hemisphere:'W'});});
test('builds checksummed GGA',()=>{assert.match(makeGga(52.3676,4.9041),/^\$GPGGA,\d{6}\.00,5222\.0560,N,00454\.2460,E,1,12,1\.0,0\.0,M,0\.0,M,,\*[0-9A-F]{2}\r\n$/);});
test('validates limits',()=>{assert.throws(()=>validate({host:'x',mountpoint:'m',username:'u',connections:9999,latitude:0,longitude:0}),/Connections/);});
test('accepts one client per CSV account',()=>{const config=validate({host:'x',mountpoint:'m',accounts:[{label:'A',username:'u1',password:'p1'},{username:'u2',password:'p2',latitude:'1.5',longitude:'2.5'}],connections:99,latitude:0,longitude:0});assert.equal(config.connections,2);assert.equal(config.accountMode,'csv');assert.equal(config.accounts[1].latitude,1.5);});
test('rejects invalid CSV account coordinates',()=>{assert.throws(()=>validate({host:'x',mountpoint:'m',accounts:[{username:'u',password:'p',latitude:91}],latitude:0,longitude:0}),/invalid latitude/);});
test('validates optional RTCM and churn controls',()=>{const config=validate({host:'x',mountpoint:'m',username:'u',latitude:0,longitude:0,parseRtcm:true,randomChurn:true,churnInterval:10,churnPercent:7,churnDowntime:2});assert.equal(config.parseRtcm,true);assert.equal(config.randomChurn,true);assert.throws(()=>validate({host:'x',mountpoint:'m',username:'u',latitude:0,longitude:0,randomChurn:true,churnInterval:1}),/Churn interval/);});
test('socket stream feeds per-client RTCM diagnostics and stop clears them',async()=>{const payload=Buffer.from([0x43,0x50]);const header=Buffer.from([0xd3,0,payload.length]);const body=Buffer.concat([header,payload]);const crc=crc24q(body);const frame=Buffer.concat([body,Buffer.from([crc>>16,(crc>>8)&255,crc&255])]);const caster=net.createServer(socket=>socket.once('data',()=>socket.write(Buffer.concat([Buffer.from('HTTP/1.1 200 OK\r\n\r\n'),frame]))));await new Promise(resolve=>caster.listen(0,'127.0.0.1',resolve));const load=new LoadTest();load.start(validate({host:'127.0.0.1',port:caster.address().port,mountpoint:'M',username:'u',password:'p',connections:1,latitude:0,longitude:0,parseRtcm:true,autoReconnect:false}));const deadline=Date.now()+2000;while((load.rtcmDetails(1)?.frames||0)<1&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,20));const details=load.rtcmDetails(1);assert.equal(details.frames,1);assert.deepEqual(details.messages,[{type:1077,count:1}]);load.stop();assert.equal(load.rtcmDetails(1),null);await new Promise(resolve=>caster.close(resolve));});
